/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum AnimationQuality implements APLEnum {

    kAnimationQualityNone(0),
    kAnimationQualitySlow(1),
    kAnimationQualityNormal(2);

    private static SparseArray<AnimationQuality> values = null;

    static {
        AnimationQuality.values = new SparseArray<>();
        AnimationQuality[] values = AnimationQuality.values();
        for (AnimationQuality value : values) {
            AnimationQuality.values.put(value.getIndex(), value);
        }
    }

    public static AnimationQuality valueOf(int idx) {
        return AnimationQuality.values.get(idx);
    }

    private final int index;

    AnimationQuality (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
