/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum AudioPlayerEventType implements APLEnum {

    kAudioPlayerEventEnd(0),
    kAudioPlayerEventPause(1),
    kAudioPlayerEventPlay(2),
    kAudioPlayerEventTimeUpdate(3),
    kAudioPlayerEventReady(4),
    kAudioPlayerEventFail(5);

    private static SparseArray<AudioPlayerEventType> values = null;

    static {
        AudioPlayerEventType.values = new SparseArray<>();
        AudioPlayerEventType[] values = AudioPlayerEventType.values();
        for (AudioPlayerEventType value : values) {
            AudioPlayerEventType.values.put(value.getIndex(), value);
        }
    }

    public static AudioPlayerEventType valueOf(int idx) {
        return AudioPlayerEventType.values.get(idx);
    }

    private final int index;

    AudioPlayerEventType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
