/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum ComponentType implements APLEnum {

    kComponentTypeContainer(0),
    kComponentTypeEditText(1),
    kComponentTypeExtension(2),
    kComponentTypeFrame(3),
    kComponentTypeGridSequence(4),
    kComponentTypeHost(5),
    kComponentTypeImage(6),
    kComponentTypePager(7),
    kComponentTypeScrollView(8),
    kComponentTypeSequence(9),
    kComponentTypeText(10),
    kComponentTypeTouchWrapper(11),
    kComponentTypeVectorGraphic(12),
    kComponentTypeVideo(13);

    private static SparseArray<ComponentType> values = null;

    static {
        ComponentType.values = new SparseArray<>();
        ComponentType[] values = ComponentType.values();
        for (ComponentType value : values) {
            ComponentType.values.put(value.getIndex(), value);
        }
    }

    public static ComponentType valueOf(int idx) {
        return ComponentType.values.get(idx);
    }

    private final int index;

    ComponentType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
