/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum ContainerDirection implements APLEnum {

    kContainerDirectionColumn(0),
    kContainerDirectionRow(1),
    kContainerDirectionColumnReverse(2),
    kContainerDirectionRowReverse(3);

    private static SparseArray<ContainerDirection> values = null;

    static {
        ContainerDirection.values = new SparseArray<>();
        ContainerDirection[] values = ContainerDirection.values();
        for (ContainerDirection value : values) {
            ContainerDirection.values.put(value.getIndex(), value);
        }
    }

    public static ContainerDirection valueOf(int idx) {
        return ContainerDirection.values.get(idx);
    }

    private final int index;

    ContainerDirection (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
