/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum EventHighlightMode implements APLEnum {

    kEventHighlightModeLine(0),
    kEventHighlightModeBlock(1);

    private static SparseArray<EventHighlightMode> values = null;

    static {
        EventHighlightMode.values = new SparseArray<>();
        EventHighlightMode[] values = EventHighlightMode.values();
        for (EventHighlightMode value : values) {
            EventHighlightMode.values.put(value.getIndex(), value);
        }
    }

    public static EventHighlightMode valueOf(int idx) {
        return EventHighlightMode.values.get(idx);
    }

    private final int index;

    EventHighlightMode (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
