/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum EventDirection implements APLEnum {

    kEventDirectionForward(0),
    kEventDirectionBackward(1);

    private static SparseArray<EventDirection> values = null;

    static {
        EventDirection.values = new SparseArray<>();
        EventDirection[] values = EventDirection.values();
        for (EventDirection value : values) {
            EventDirection.values.put(value.getIndex(), value);
        }
    }

    public static EventDirection valueOf(int idx) {
        return EventDirection.values.get(idx);
    }

    private final int index;

    EventDirection (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
