/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum EventReason implements APLEnum {

    kEventReasonBack(0),
    kEventReasonExit(1);

    private static SparseArray<EventReason> values = null;

    static {
        EventReason.values = new SparseArray<>();
        EventReason[] values = EventReason.values();
        for (EventReason value : values) {
            EventReason.values.put(value.getIndex(), value);
        }
    }

    public static EventReason valueOf(int idx) {
        return EventReason.values.get(idx);
    }

    private final int index;

    EventReason (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
