/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum EventScrollAlign implements APLEnum {

    kEventScrollAlignFirst(0),
    kEventScrollAlignCenter(1),
    kEventScrollAlignLast(2),
    kEventScrollAlignVisible(3);

    private static SparseArray<EventScrollAlign> values = null;

    static {
        EventScrollAlign.values = new SparseArray<>();
        EventScrollAlign[] values = EventScrollAlign.values();
        for (EventScrollAlign value : values) {
            EventScrollAlign.values.put(value.getIndex(), value);
        }
    }

    public static EventScrollAlign valueOf(int idx) {
        return EventScrollAlign.values.get(idx);
    }

    private final int index;

    EventScrollAlign (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
