/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum EventAudioTrack implements APLEnum {

    kEventAudioTrackBackground(0),
    kEventAudioTrackForeground(1),
    kEventAudioTrackNone(2);

    private static SparseArray<EventAudioTrack> values = null;

    static {
        EventAudioTrack.values = new SparseArray<>();
        EventAudioTrack[] values = EventAudioTrack.values();
        for (EventAudioTrack value : values) {
            EventAudioTrack.values.put(value.getIndex(), value);
        }
    }

    public static EventAudioTrack valueOf(int idx) {
        return EventAudioTrack.values.get(idx);
    }

    private final int index;

    EventAudioTrack (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
