/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum EventControlMediaCommand implements APLEnum {

    kEventControlMediaPlay(0),
    kEventControlMediaPause(1),
    kEventControlMediaNext(2),
    kEventControlMediaPrevious(3),
    kEventControlMediaRewind(4),
    kEventControlMediaSeek(5),
    kEventControlMediaSetTrack(7);

    private static SparseArray<EventControlMediaCommand> values = null;

    static {
        EventControlMediaCommand.values = new SparseArray<>();
        EventControlMediaCommand[] values = EventControlMediaCommand.values();
        for (EventControlMediaCommand value : values) {
            EventControlMediaCommand.values.put(value.getIndex(), value);
        }
    }

    public static EventControlMediaCommand valueOf(int idx) {
        return EventControlMediaCommand.values.get(idx);
    }

    private final int index;

    EventControlMediaCommand (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
