/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum EventProperty implements APLEnum {

    kEventPropertyAlign(0),
    kEventPropertyArguments(1),
    kEventPropertyAudioTrack(2),
    kEventPropertyCommand(3),
    kEventPropertyComponent(4),
    kEventPropertyComponents(5),
    kEventPropertyDirection(6),
    kEventPropertyExtension(7),
    kEventPropertyExtensionURI(8),
    kEventPropertyExtensionResourceId(9),
    kEventPropertyFlags(10),
    kEventPropertyHeaders(11),
    kEventPropertyHighlightMode(12),
    kEventPropertyMediaType(13),
    kEventPropertyName(14),
    kEventPropertyPosition(15),
    kEventPropertyRangeStart(16),
    kEventPropertyRangeEnd(17),
    kEventPropertyReason(18),
    kEventPropertySource(19),
    kEventPropertyValue(20);

    private static SparseArray<EventProperty> values = null;

    static {
        EventProperty.values = new SparseArray<>();
        EventProperty[] values = EventProperty.values();
        for (EventProperty value : values) {
            EventProperty.values.put(value.getIndex(), value);
        }
    }

    public static EventProperty valueOf(int idx) {
        return EventProperty.values.get(idx);
    }

    private final int index;

    EventProperty (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
