/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum ExtensionComponentResourceState implements APLEnum {

    /// The resource is needed, but has not been created
    kResourcePending(0),
    /// The resource required by component is available
    kResourceReady(1),
    /// The resource has been released normally
    kResourceReleased(2),
    /// The resource has failed creation or experienced and error
    kResourceError(3);

    private static SparseArray<ExtensionComponentResourceState> values = null;

    static {
        ExtensionComponentResourceState.values = new SparseArray<>();
        ExtensionComponentResourceState[] values = ExtensionComponentResourceState.values();
        for (ExtensionComponentResourceState value : values) {
            ExtensionComponentResourceState.values.put(value.getIndex(), value);
        }
    }

    public static ExtensionComponentResourceState valueOf(int idx) {
        return ExtensionComponentResourceState.values.get(idx);
    }

    private final int index;

    ExtensionComponentResourceState (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
