/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum FilterProperty implements APLEnum {

    /// Amount (used in Grayscale, Saturate)
    kFilterPropertyAmount(0),
    /// Solid color
    kFilterPropertyColor(1),
    /// Destination image index
    kFilterPropertyDestination(2),
    /// Extension properties
    kFilterPropertyExtension(3),
    /// URI of the extension filter
    kFilterPropertyExtensionURI(4),
    /// Gradient
    kFilterPropertyGradient(5),
    /// Noise type enumerated value
    kFilterPropertyKind(6),
    /// Blend mode
    kFilterPropertyMode(7),
    /// Name of the extension filter
    kFilterPropertyName(8),
    /// Blur radius (dimension)
    kFilterPropertyRadius(9),
    /// Noise standard deviation (number)
    kFilterPropertySigma(10),
    /// Source image index
    kFilterPropertySource(11),
    /// Noise use color flag (boolean)
    kFilterPropertyUseColor(12);

    private static SparseArray<FilterProperty> values = null;

    static {
        FilterProperty.values = new SparseArray<>();
        FilterProperty[] values = FilterProperty.values();
        for (FilterProperty value : values) {
            FilterProperty.values.put(value.getIndex(), value);
        }
    }

    public static FilterProperty valueOf(int idx) {
        return FilterProperty.values.get(idx);
    }

    private final int index;

    FilterProperty (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
