/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum FilterType implements APLEnum {

    kFilterTypeBlend(0),
    kFilterTypeBlur(1),
    kFilterTypeColor(2),
    kFilterTypeExtension(3),
    kFilterTypeGradient(4),
    kFilterTypeGrayscale(5),
    kFilterTypeNoise(6),
    kFilterTypeSaturate(7);

    private static SparseArray<FilterType> values = null;

    static {
        FilterType.values = new SparseArray<>();
        FilterType[] values = FilterType.values();
        for (FilterType value : values) {
            FilterType.values.put(value.getIndex(), value);
        }
    }

    public static FilterType valueOf(int idx) {
        return FilterType.values.get(idx);
    }

    private final int index;

    FilterType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
