/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum FlexboxJustifyContent implements APLEnum {

    kFlexboxJustifyContentStart(0),
    kFlexboxJustifyContentEnd(1),
    kFlexboxJustifyContentCenter(2),
    kFlexboxJustifyContentSpaceBetween(3),
    kFlexboxJustifyContentSpaceAround(4);

    private static SparseArray<FlexboxJustifyContent> values = null;

    static {
        FlexboxJustifyContent.values = new SparseArray<>();
        FlexboxJustifyContent[] values = FlexboxJustifyContent.values();
        for (FlexboxJustifyContent value : values) {
            FlexboxJustifyContent.values.put(value.getIndex(), value);
        }
    }

    public static FlexboxJustifyContent valueOf(int idx) {
        return FlexboxJustifyContent.values.get(idx);
    }

    private final int index;

    FlexboxJustifyContent (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
