/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum FlexboxAlign implements APLEnum {

    kFlexboxAlignStretch(0),
    kFlexboxAlignCenter(1),
    kFlexboxAlignStart(2),
    kFlexboxAlignEnd(3),
    kFlexboxAlignBaseline(4),
    kFlexboxAlignAuto(5);

    private static SparseArray<FlexboxAlign> values = null;

    static {
        FlexboxAlign.values = new SparseArray<>();
        FlexboxAlign[] values = FlexboxAlign.values();
        for (FlexboxAlign value : values) {
            FlexboxAlign.values.put(value.getIndex(), value);
        }
    }

    public static FlexboxAlign valueOf(int idx) {
        return FlexboxAlign.values.get(idx);
    }

    private final int index;

    FlexboxAlign (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
