/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum FocusDirection implements APLEnum {

    kFocusDirectionNone(0),
    kFocusDirectionForward(1),
    kFocusDirectionBackwards(2),
    kFocusDirectionUp(3),
    kFocusDirectionDown(4),
    kFocusDirectionLeft(5),
    kFocusDirectionRight(6);

    private static SparseArray<FocusDirection> values = null;

    static {
        FocusDirection.values = new SparseArray<>();
        FocusDirection[] values = FocusDirection.values();
        for (FocusDirection value : values) {
            FocusDirection.values.put(value.getIndex(), value);
        }
    }

    public static FocusDirection valueOf(int idx) {
        return FocusDirection.values.get(idx);
    }

    private final int index;

    FocusDirection (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
