/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum FontStyle implements APLEnum {

    kFontStyleNormal(0),
    kFontStyleItalic(1);

    private static SparseArray<FontStyle> values = null;

    static {
        FontStyle.values = new SparseArray<>();
        FontStyle[] values = FontStyle.values();
        for (FontStyle value : values) {
            FontStyle.values.put(value.getIndex(), value);
        }
    }

    public static FontStyle valueOf(int idx) {
        return FontStyle.values.get(idx);
    }

    private final int index;

    FontStyle (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
