/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GradientUnits implements APLEnum {

    kGradientUnitsBoundingBox(0),
    kGradientUnitsUserSpace(1);

    private static SparseArray<GradientUnits> values = null;

    static {
        GradientUnits.values = new SparseArray<>();
        GradientUnits[] values = GradientUnits.values();
        for (GradientUnits value : values) {
            GradientUnits.values.put(value.getIndex(), value);
        }
    }

    public static GradientUnits valueOf(int idx) {
        return GradientUnits.values.get(idx);
    }

    private final int index;

    GradientUnits (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
