/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GradientProperty implements APLEnum {

    kGradientPropertyType(0),
    kGradientPropertyColorRange(1),
    kGradientPropertyInputRange(2),
    kGradientPropertyAngle(3),
    kGradientPropertySpreadMethod(4),
    kGradientPropertyX1(5),
    kGradientPropertyY1(6),
    kGradientPropertyX2(7),
    kGradientPropertyY2(8),
    kGradientPropertyCenterX(9),
    kGradientPropertyCenterY(10),
    kGradientPropertyRadius(11),
    kGradientPropertyUnits(12);

    private static SparseArray<GradientProperty> values = null;

    static {
        GradientProperty.values = new SparseArray<>();
        GradientProperty[] values = GradientProperty.values();
        for (GradientProperty value : values) {
            GradientProperty.values.put(value.getIndex(), value);
        }
    }

    public static GradientProperty valueOf(int idx) {
        return GradientProperty.values.get(idx);
    }

    private final int index;

    GradientProperty (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
