/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GradientType implements APLEnum {

    /** Linear gradient */
    LINEAR(0),
    /** Radial gradient, centered about the center of an object */
    RADIAL(1);

    private static SparseArray<GradientType> values = null;

    static {
        GradientType.values = new SparseArray<>();
        GradientType[] values = GradientType.values();
        for (GradientType value : values) {
            GradientType.values.put(value.getIndex(), value);
        }
    }

    public static GradientType valueOf(int idx) {
        return GradientType.values.get(idx);
    }

    private final int index;

    GradientType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
