/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GraphicLayoutDirection implements APLEnum {

    kGraphicLayoutDirectionLTR(0),
    kGraphicLayoutDirectionRTL(1);

    private static SparseArray<GraphicLayoutDirection> values = null;

    static {
        GraphicLayoutDirection.values = new SparseArray<>();
        GraphicLayoutDirection[] values = GraphicLayoutDirection.values();
        for (GraphicLayoutDirection value : values) {
            GraphicLayoutDirection.values.put(value.getIndex(), value);
        }
    }

    public static GraphicLayoutDirection valueOf(int idx) {
        return GraphicLayoutDirection.values.get(idx);
    }

    private final int index;

    GraphicLayoutDirection (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
