/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GraphicElementType implements APLEnum {

    kGraphicElementTypeContainer(0),
    kGraphicElementTypeGroup(1),
    kGraphicElementTypePath(2),
    kGraphicElementTypeText(3);

    private static SparseArray<GraphicElementType> values = null;

    static {
        GraphicElementType.values = new SparseArray<>();
        GraphicElementType[] values = GraphicElementType.values();
        for (GraphicElementType value : values) {
            GraphicElementType.values.put(value.getIndex(), value);
        }
    }

    public static GraphicElementType valueOf(int idx) {
        return GraphicElementType.values.get(idx);
    }

    private final int index;

    GraphicElementType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
