/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GraphicScale implements APLEnum {

    kGraphicScaleNone(0),
    kGraphicScaleGrow(1),
    kGraphicScaleShrink(2),
    kGraphicScaleStretch(3);

    private static SparseArray<GraphicScale> values = null;

    static {
        GraphicScale.values = new SparseArray<>();
        GraphicScale[] values = GraphicScale.values();
        for (GraphicScale value : values) {
            GraphicScale.values.put(value.getIndex(), value);
        }
    }

    public static GraphicScale valueOf(int idx) {
        return GraphicScale.values.get(idx);
    }

    private final int index;

    GraphicScale (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
