/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GraphicFilterProperty implements APLEnum {

    /// Color of the shadow
    kGraphicPropertyFilterColor(0),
    /// Horizontal offset of the shadow
    kGraphicPropertyFilterHorizontalOffset(1),
    /// Blur radius of the shadow
    kGraphicPropertyFilterRadius(2),
    /// Vertical offset of the shadow
    kGraphicPropertyFilterVerticalOffset(3);

    private static SparseArray<GraphicFilterProperty> values = null;

    static {
        GraphicFilterProperty.values = new SparseArray<>();
        GraphicFilterProperty[] values = GraphicFilterProperty.values();
        for (GraphicFilterProperty value : values) {
            GraphicFilterProperty.values.put(value.getIndex(), value);
        }
    }

    public static GraphicFilterProperty valueOf(int idx) {
        return GraphicFilterProperty.values.get(idx);
    }

    private final int index;

    GraphicFilterProperty (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
