/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GraphicLineJoin implements APLEnum {

    kGraphicLineJoinBevel(0),
    kGraphicLineJoinMiter(1),
    kGraphicLineJoinRound(2);

    private static SparseArray<GraphicLineJoin> values = null;

    static {
        GraphicLineJoin.values = new SparseArray<>();
        GraphicLineJoin[] values = GraphicLineJoin.values();
        for (GraphicLineJoin value : values) {
            GraphicLineJoin.values.put(value.getIndex(), value);
        }
    }

    public static GraphicLineJoin valueOf(int idx) {
        return GraphicLineJoin.values.get(idx);
    }

    private final int index;

    GraphicLineJoin (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
