/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GraphicPropertyKey implements APLEnum {

    kGraphicPropertyClipPath(0),
    kGraphicPropertyCoordinateX(1),
    kGraphicPropertyCoordinateY(2),
    kGraphicPropertyFill(3),
    kGraphicPropertyFillOpacity(4),
    kGraphicPropertyFillTransform(5),
    kGraphicPropertyFillTransformAssigned(6),
    kGraphicPropertyFilters(7),
    kGraphicPropertyFontFamily(8),
    kGraphicPropertyFontSize(9),
    kGraphicPropertyFontStyle(10),
    kGraphicPropertyFontWeight(11),
    kGraphicPropertyHeightActual(12),
    kGraphicPropertyHeightOriginal(13),
    kGraphicPropertyLang(14),
    kGraphicPropertyLayoutDirection(15),
    kGraphicPropertyLetterSpacing(16),
    kGraphicPropertyOpacity(17),
    kGraphicPropertyPathData(18),
    kGraphicPropertyPathLength(19),
    kGraphicPropertyPivotX(20),
    kGraphicPropertyPivotY(21),
    kGraphicPropertyRotation(22),
    kGraphicPropertyScaleX(23),
    kGraphicPropertyScaleY(24),
    kGraphicPropertyViewportHeightActual(25),
    kGraphicPropertyViewportWidthActual(26),
    kGraphicPropertyScaleTypeHeight(27),
    kGraphicPropertyScaleTypeWidth(28),
    kGraphicPropertyStroke(29),
    kGraphicPropertyStrokeDashArray(30),
    kGraphicPropertyStrokeDashOffset(31),
    kGraphicPropertyStrokeLineCap(32),
    kGraphicPropertyStrokeLineJoin(33),
    kGraphicPropertyStrokeMiterLimit(34),
    kGraphicPropertyStrokeOpacity(35),
    kGraphicPropertyStrokeTransform(36),
    kGraphicPropertyStrokeTransformAssigned(37),
    kGraphicPropertyStrokeWidth(38),
    kGraphicPropertyText(39),
    kGraphicPropertyTextAnchor(40),
    kGraphicPropertyTransform(41),
    kGraphicPropertyTransformAssigned(42),
    kGraphicPropertyTranslateX(43),
    kGraphicPropertyTranslateY(44),
    kGraphicPropertyVersion(45),
    kGraphicPropertyViewportHeightOriginal(46),
    kGraphicPropertyViewportWidthOriginal(47),
    kGraphicPropertyWidthActual(48),
    kGraphicPropertyWidthOriginal(49);

    private static SparseArray<GraphicPropertyKey> values = null;

    static {
        GraphicPropertyKey.values = new SparseArray<>();
        GraphicPropertyKey[] values = GraphicPropertyKey.values();
        for (GraphicPropertyKey value : values) {
            GraphicPropertyKey.values.put(value.getIndex(), value);
        }
    }

    public static GraphicPropertyKey valueOf(int idx) {
        return GraphicPropertyKey.values.get(idx);
    }

    private final int index;

    GraphicPropertyKey (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
