/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GraphicFilterType implements APLEnum {

    kGraphicFilterTypeDropShadow(0);

    private static SparseArray<GraphicFilterType> values = null;

    static {
        GraphicFilterType.values = new SparseArray<>();
        GraphicFilterType[] values = GraphicFilterType.values();
        for (GraphicFilterType value : values) {
            GraphicFilterType.values.put(value.getIndex(), value);
        }
    }

    public static GraphicFilterType valueOf(int idx) {
        return GraphicFilterType.values.get(idx);
    }

    private final int index;

    GraphicFilterType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
