/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum GraphicLineCap implements APLEnum {

    kGraphicLineCapButt(0),
    kGraphicLineCapRound(1),
    kGraphicLineCapSquare(2);

    private static SparseArray<GraphicLineCap> values = null;

    static {
        GraphicLineCap.values = new SparseArray<>();
        GraphicLineCap[] values = GraphicLineCap.values();
        for (GraphicLineCap value : values) {
            GraphicLineCap.values.put(value.getIndex(), value);
        }
    }

    public static GraphicLineCap valueOf(int idx) {
        return GraphicLineCap.values.get(idx);
    }

    private final int index;

    GraphicLineCap (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
