/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum ImageScale implements APLEnum {

    kImageScaleNone(0),
    kImageScaleFill(1),
    kImageScaleBestFill(2),
    kImageScaleBestFit(3),
    kImageScaleBestFitDown(4);

    private static SparseArray<ImageScale> values = null;

    static {
        ImageScale.values = new SparseArray<>();
        ImageScale[] values = ImageScale.values();
        for (ImageScale value : values) {
            ImageScale.values.put(value.getIndex(), value);
        }
    }

    public static ImageScale valueOf(int idx) {
        return ImageScale.values.get(idx);
    }

    private final int index;

    ImageScale (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
