/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum KeyHandlerType implements APLEnum {

    /**     * This view host has received a key press and should execute the key handlers     * specified by the 'handleKeyDown' property, if any, on the focused component.     */
    kKeyDown(0),
    /**     * This view host has received a key release and should execute the key handlers     * specified by the 'handleKeyUp' property, if any, on the focused component.     */
    kKeyUp(1);

    private static SparseArray<KeyHandlerType> values = null;

    static {
        KeyHandlerType.values = new SparseArray<>();
        KeyHandlerType[] values = KeyHandlerType.values();
        for (KeyHandlerType value : values) {
            KeyHandlerType.values.put(value.getIndex(), value);
        }
    }

    public static KeyHandlerType valueOf(int idx) {
        return KeyHandlerType.values.get(idx);
    }

    private final int index;

    KeyHandlerType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
