/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum LayoutDirection implements APLEnum {

    /// Inherit is for input only, and will not be send out as output value.
    kLayoutDirectionInherit(0),
    kLayoutDirectionLTR(1),
    kLayoutDirectionRTL(2);

    private static SparseArray<LayoutDirection> values = null;

    static {
        LayoutDirection.values = new SparseArray<>();
        LayoutDirection[] values = LayoutDirection.values();
        for (LayoutDirection value : values) {
            LayoutDirection.values.put(value.getIndex(), value);
        }
    }

    public static LayoutDirection valueOf(int idx) {
        return LayoutDirection.values.get(idx);
    }

    private final int index;

    LayoutDirection (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
