/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum MediaPlayerEventType implements APLEnum {

    kMediaPlayerEventEnd(0),
    kMediaPlayerEventPause(1),
    kMediaPlayerEventPlay(2),
    kMediaPlayerEventTimeUpdate(3),
    kMediaPlayerEventTrackUpdate(4),
    kMediaPlayerEventTrackReady(5),
    kMediaPlayerEventTrackFail(6);

    private static SparseArray<MediaPlayerEventType> values = null;

    static {
        MediaPlayerEventType.values = new SparseArray<>();
        MediaPlayerEventType[] values = MediaPlayerEventType.values();
        for (MediaPlayerEventType value : values) {
            MediaPlayerEventType.values.put(value.getIndex(), value);
        }
    }

    public static MediaPlayerEventType valueOf(int idx) {
        return MediaPlayerEventType.values.get(idx);
    }

    private final int index;

    MediaPlayerEventType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
