/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum Navigation implements APLEnum {

    kNavigationNormal(0),
    kNavigationNone(1),
    kNavigationWrap(2),
    kNavigationForwardOnly(3);

    private static SparseArray<Navigation> values = null;

    static {
        Navigation.values = new SparseArray<>();
        Navigation[] values = Navigation.values();
        for (Navigation value : values) {
            Navigation.values.put(value.getIndex(), value);
        }
    }

    public static Navigation valueOf(int idx) {
        return Navigation.values.get(idx);
    }

    private final int index;

    Navigation (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
