/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum NoiseFilterKind implements APLEnum {

    kFilterNoiseKindUniform(0),
    kFilterNoiseKindGaussian(1);

    private static SparseArray<NoiseFilterKind> values = null;

    static {
        NoiseFilterKind.values = new SparseArray<>();
        NoiseFilterKind[] values = NoiseFilterKind.values();
        for (NoiseFilterKind value : values) {
            NoiseFilterKind.values.put(value.getIndex(), value);
        }
    }

    public static NoiseFilterKind valueOf(int idx) {
        return NoiseFilterKind.values.get(idx);
    }

    private final int index;

    NoiseFilterKind (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
