/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum PointerType implements APLEnum {

    /// Indicates the pointer is a mouse type
    kMousePointer(0),
    /// Indicates the pointer originates as a touch input
    kTouchPointer(1);

    private static SparseArray<PointerType> values = null;

    static {
        PointerType.values = new SparseArray<>();
        PointerType[] values = PointerType.values();
        for (PointerType value : values) {
            PointerType.values.put(value.getIndex(), value);
        }
    }

    public static PointerType valueOf(int idx) {
        return PointerType.values.get(idx);
    }

    private final int index;

    PointerType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
