/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum Position implements APLEnum {

    kPositionAbsolute(0),
    kPositionRelative(1),
    kPositionSticky(2);

    private static SparseArray<Position> values = null;

    static {
        Position.values = new SparseArray<>();
        Position[] values = Position.values();
        for (Position value : values) {
            Position.values.put(value.getIndex(), value);
        }
    }

    public static Position valueOf(int idx) {
        return Position.values.get(idx);
    }

    private final int index;

    Position (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
