/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum ScreenShape implements APLEnum {

    RECTANGLE(0),
    ROUND(1);

    private static SparseArray<ScreenShape> values = null;

    static {
        ScreenShape.values = new SparseArray<>();
        ScreenShape[] values = ScreenShape.values();
        for (ScreenShape value : values) {
            ScreenShape.values.put(value.getIndex(), value);
        }
    }

    public static ScreenShape valueOf(int idx) {
        return ScreenShape.values.get(idx);
    }

    private final int index;

    ScreenShape (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
