/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum ScreenMode implements APLEnum {

    kScreenModeNormal(0),
    kScreenModeHighContrast(1);

    private static SparseArray<ScreenMode> values = null;

    static {
        ScreenMode.values = new SparseArray<>();
        ScreenMode[] values = ScreenMode.values();
        for (ScreenMode value : values) {
            ScreenMode.values.put(value.getIndex(), value);
        }
    }

    public static ScreenMode valueOf(int idx) {
        return ScreenMode.values.get(idx);
    }

    private final int index;

    ScreenMode (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
