/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum ScrollDirection implements APLEnum {

    kScrollDirectionVertical(0),
    kScrollDirectionHorizontal(1);

    private static SparseArray<ScrollDirection> values = null;

    static {
        ScrollDirection.values = new SparseArray<>();
        ScrollDirection[] values = ScrollDirection.values();
        for (ScrollDirection value : values) {
            ScrollDirection.values.put(value.getIndex(), value);
        }
    }

    public static ScrollDirection valueOf(int idx) {
        return ScrollDirection.values.get(idx);
    }

    private final int index;

    ScrollDirection (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
