/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum Snap implements APLEnum {

    kSnapNone(0),
    kSnapStart(1),
    kSnapCenter(2),
    kSnapEnd(3),
    kSnapForceStart(4),
    kSnapForceCenter(5),
    kSnapForceEnd(6);

    private static SparseArray<Snap> values = null;

    static {
        Snap.values = new SparseArray<>();
        Snap[] values = Snap.values();
        for (Snap value : values) {
            Snap.values.put(value.getIndex(), value);
        }
    }

    public static Snap valueOf(int idx) {
        return Snap.values.get(idx);
    }

    private final int index;

    Snap (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
