/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum SpanAttributeName implements APLEnum {

    kSpanAttributeNameColor(0),
    kSpanAttributeNameFontSize(1);

    private static SparseArray<SpanAttributeName> values = null;

    static {
        SpanAttributeName.values = new SparseArray<>();
        SpanAttributeName[] values = SpanAttributeName.values();
        for (SpanAttributeName value : values) {
            SpanAttributeName.values.put(value.getIndex(), value);
        }
    }

    public static SpanAttributeName valueOf(int idx) {
        return SpanAttributeName.values.get(idx);
    }

    private final int index;

    SpanAttributeName (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
