/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum SpanType implements APLEnum {

    kSpanTypeLineBreak(0),
    kSpanTypeStrong(1),
    kSpanTypeItalic(2),
    kSpanTypeStrike(3),
    kSpanTypeUnderline(4),
    kSpanTypeMonospace(5),
    kSpanTypeSuperscript(6),
    kSpanTypeSubscript(7),
    kSpanTypeNoBreak(8),
    kSpanTypeSpan(9),
    kSpanTypeListItem(10);

    private static SparseArray<SpanType> values = null;

    static {
        SpanType.values = new SparseArray<>();
        SpanType[] values = SpanType.values();
        for (SpanType value : values) {
            SpanType.values.put(value.getIndex(), value);
        }
    }

    public static SpanType valueOf(int idx) {
        return SpanType.values.get(idx);
    }

    private final int index;

    SpanType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
