/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum SubmitKeyType implements APLEnum {

    kSubmitKeyTypeDone(0),
    kSubmitKeyTypeGo(1),
    kSubmitKeyTypeNext(2),
    kSubmitKeyTypeSearch(3),
    kSubmitKeyTypeSend(4);

    private static SparseArray<SubmitKeyType> values = null;

    static {
        SubmitKeyType.values = new SparseArray<>();
        SubmitKeyType[] values = SubmitKeyType.values();
        for (SubmitKeyType value : values) {
            SubmitKeyType.values.put(value.getIndex(), value);
        }
    }

    public static SubmitKeyType valueOf(int idx) {
        return SubmitKeyType.values.get(idx);
    }

    private final int index;

    SubmitKeyType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
