/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum TextAlign implements APLEnum {

    kTextAlignAuto(0),
    kTextAlignLeft(1),
    kTextAlignCenter(2),
    kTextAlignRight(3),
    kTextAlignStart(4),
    kTextAlignEnd(5);

    private static SparseArray<TextAlign> values = null;

    static {
        TextAlign.values = new SparseArray<>();
        TextAlign[] values = TextAlign.values();
        for (TextAlign value : values) {
            TextAlign.values.put(value.getIndex(), value);
        }
    }

    public static TextAlign valueOf(int idx) {
        return TextAlign.values.get(idx);
    }

    private final int index;

    TextAlign (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
