/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum TextAlignVertical implements APLEnum {

    kTextAlignVerticalAuto(0),
    kTextAlignVerticalTop(1),
    kTextAlignVerticalCenter(2),
    kTextAlignVerticalBottom(3);

    private static SparseArray<TextAlignVertical> values = null;

    static {
        TextAlignVertical.values = new SparseArray<>();
        TextAlignVertical[] values = TextAlignVertical.values();
        for (TextAlignVertical value : values) {
            TextAlignVertical.values.put(value.getIndex(), value);
        }
    }

    public static TextAlignVertical valueOf(int idx) {
        return TextAlignVertical.values.get(idx);
    }

    private final int index;

    TextAlignVertical (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
