/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum TokenType implements APLEnum {

    kStartSpan(0),
    kEndSpan(1),
    kString(2),
    kEnd(3);

    private static SparseArray<TokenType> values = null;

    static {
        TokenType.values = new SparseArray<>();
        TokenType[] values = TokenType.values();
        for (TokenType value : values) {
            TokenType.values.put(value.getIndex(), value);
        }
    }

    public static TokenType valueOf(int idx) {
        return TokenType.values.get(idx);
    }

    private final int index;

    TokenType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
