/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum TrackState implements APLEnum {

    /// Playback cannot start in this state as player still need to prepare/ load the media source.
    kTrackNotReady(0),
    /// Track is ready for playback i.e player has loaded meta data and media information required to start the playback.
    kTrackReady(1),
    /// when player fails to load the media or if media is malformed or unsupported.
    kTrackFailed(2);

    private static SparseArray<TrackState> values = null;

    static {
        TrackState.values = new SparseArray<>();
        TrackState[] values = TrackState.values();
        for (TrackState value : values) {
            TrackState.values.put(value.getIndex(), value);
        }
    }

    public static TrackState valueOf(int idx) {
        return TrackState.values.get(idx);
    }

    private final int index;

    TrackState (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
