/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum UpdateType implements APLEnum {

    ///@deprecated
    kUpdatePressed(0),
    /**     * This component should take keyboard focus.     */
    kUpdateTakeFocus(1),
    ///@deprecated
    kUpdatePressState(2),
    ///@deprecated
    kUpdateScrollPosition(3),
    ///@deprecated
    kUpdatePagerPosition(4),
    ///@deprecated
    kUpdatePagerByEvent(5),
    /**     * The user has pressed the submit button associated with a EditText component.     */
    kUpdateSubmit(6),
    /**     * The user has changed the text in the edit text component.     */
    kUpdateTextChange(7),
    /**      * Invoke an accessibility action by name.  The argument is the string name of the action to invoke.      */
    kUpdateAccessibilityAction(8);

    private static SparseArray<UpdateType> values = null;

    static {
        UpdateType.values = new SparseArray<>();
        UpdateType[] values = UpdateType.values();
        for (UpdateType value : values) {
            UpdateType.values.put(value.getIndex(), value);
        }
    }

    public static UpdateType valueOf(int idx) {
        return UpdateType.values.get(idx);
    }

    private final int index;

    UpdateType (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
