/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum VectorGraphicAlign implements APLEnum {

    kVectorGraphicAlignBottom(0),
    kVectorGraphicAlignBottomLeft(1),
    kVectorGraphicAlignBottomRight(2),
    kVectorGraphicAlignCenter(3),
    kVectorGraphicAlignLeft(4),
    kVectorGraphicAlignRight(5),
    kVectorGraphicAlignTop(6),
    kVectorGraphicAlignTopLeft(7),
    kVectorGraphicAlignTopRight(8);

    private static SparseArray<VectorGraphicAlign> values = null;

    static {
        VectorGraphicAlign.values = new SparseArray<>();
        VectorGraphicAlign[] values = VectorGraphicAlign.values();
        for (VectorGraphicAlign value : values) {
            VectorGraphicAlign.values.put(value.getIndex(), value);
        }
    }

    public static VectorGraphicAlign valueOf(int idx) {
        return VectorGraphicAlign.values.get(idx);
    }

    private final int index;

    VectorGraphicAlign (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
