/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum VideoScale implements APLEnum {

    kVideoScaleBestFill(0),
    kVideoScaleBestFit(1);

    private static SparseArray<VideoScale> values = null;

    static {
        VideoScale.values = new SparseArray<>();
        VideoScale[] values = VideoScale.values();
        for (VideoScale value : values) {
            VideoScale.values.put(value.getIndex(), value);
        }
    }

    public static VideoScale valueOf(int idx) {
        return VideoScale.values.get(idx);
    }

    private final int index;

    VideoScale (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
