/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */

/*
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */

package com.amazon.apl.enums;

import android.util.SparseArray;

public enum ViewportMode implements APLEnum {

    /// Automotive or vehicle
    kViewportModeAuto(0),
    /// Desktop or countertop
    kViewportModeHub(1),
    /// Mobile phone or tablet
    kViewportModeMobile(2),
    /// Desktop or laptop PC
    kViewportModePC(3),
    /// Television
    kViewportModeTV(4);

    private static SparseArray<ViewportMode> values = null;

    static {
        ViewportMode.values = new SparseArray<>();
        ViewportMode[] values = ViewportMode.values();
        for (ViewportMode value : values) {
            ViewportMode.values.put(value.getIndex(), value);
        }
    }

    public static ViewportMode valueOf(int idx) {
        return ViewportMode.values.get(idx);
    }

    private final int index;

    ViewportMode (int index) {
        this.index = index;
    }

    @Override
    public int getIndex() { return this.index; }
}
